### ISSUE TITLE
Import the new manipulator's URDF

### ISSUE THREAD

**Issue by Jack-XingLi** [dexsuite/dex-retargeting#19]
Hi @yzqin ，
Your work has left a deep impression on me, but I am currently encountering issues while using the code. I am attempting to import a humanoid three-finger dexterous hand, consisting of a thumb, index finger, and middle finger. I have imported the URDF, but it seems that the redirection process has encountered some problems. I would like to inquire if there are any specific considerations to keep in mind when importing URDF files. I look forward to your response. Thank you!
![截图 2024-06-07 12-18-40](https://github.com/dexsuite/dex-retargeting/assets/139104455/ea90c88e-84fc-4b01-821e-24a5383f4436)
When my humanoid hand is fully extended, the robotic hand does not synchronize with mine; instead, it bends to 90 degrees.

**Comment by yzqin** [comment]
hi @Jack-XingLi 

Thanks for the kind words. Yes there are some specific considerations for the hand definition. To use dex-retargeting, we assume that the root of your hand should be consistent with some conventions.

Right hand: x->forward, z->from wrist to tip, y->pinky to thumb
Left hand: x->forward, z->from wrist to tip, y-> thumb to pinky

An visualization can be found below. 

![image](https://github.com/dexsuite/dex-retargeting/assets/24649446/4abdc2fe-6ef2-4db4-a1e0-eb753c99d8e4)

I have made some effort to ensure that all models we used in our repo, such as [dex-urdf](https://github.com/dexsuite/dex-urdf), [bunny_vision_pro](https://github.com/Dingry/BunnyVisionPro), and the customized robot hand design in [from-one-hand-to-multiple-hand](https://github.com/yzqin/dex-hand-teleop), will follow this convention. So that if you use any hands from dex-urdf, it will work out of the box. For your new hand, you may also need to rotate the urdf so that it follows the same convention.

By the way, may I ask what is the name of your humanoid robot hand?

**Comment by Jack-XingLi** [comment]
hi, @yzqin :
Thank you for your prompt reply. This hand is a prototype made in our lab, very similar to the Leaphand, except it lacks a ring finger, and the thumb has only 3 degrees of freedom. I've adjusted the base coordinate system to meet specific requirements, but it seems I haven't successfully resolved my issue. Below is how my hand looks when extended, but after redirection, the robotic hand tends to bend to 90 degrees, while my hand is extended. I suspect it's an issue with the redirection coefficient, but despite many adjustments, I haven't been able to solve the problem effectively. Do you have any suggestions? Thank you!
![截图 2024-06-07 14-27-57](https://github.com/dexsuite/dex-retargeting/assets/139104455/9f01ff5a-970a-44bd-9732-1cd19c171ddd)
![截图 2024-06-07 14-38-50](https://github.com/dexsuite/dex-retargeting/assets/139104455/84a4103f-a1fd-414b-b322-6a4d0ed61ba5)
![截图 2024-06-07 14-39-19](https://github.com/dexsuite/dex-retargeting/assets/139104455/6cca5f67-1308-45a6-ab60-65981bd7a1af)
![截图 2024-06-07 14-41-32](https://github.com/dexsuite/dex-retargeting/assets/139104455/304b2535-36e6-48a8-a2a2-d49970e94d69)

**Comment by Jack-XingLi** [comment]
I have solved the problem, the main reason was the URDF itself, thank you for your work!

**Comment by yzqin** [comment]
Glad to hear that you were able to resolve the problem! I apologize for not being able to provide more assistance in this case. Without a complete URDF file, it was a bit challenging for me to fully grasp the context of the issue you were experiencing.

Since the problem has been solved, I will go ahead and close this issue. If you encounter any further difficulties or have additional questions, please don't hesitate to open a new issue with more detailed information, including the relevant URDF file if possible.

**Comment by boreep** [comment]
> hi, [@yzqin](https://github.com/yzqin) : Thank you for your prompt reply. This hand is a prototype made in our lab, very similar to the Leaphand, except it lacks a ring finger, and the thumb has only 3 degrees of freedom. I've adjusted the base coordinate system to meet specific requirements, but it seems I haven't successfully resolved my issue. Below is how my hand looks when extended, but after redirection, the robotic hand tends to bend to 90 degrees, while my hand is extended. I suspect it's an issue with the redirection coefficient, but despite many adjustments, I haven't been able to solve the problem effectively. Do you have any suggestions? Thank you! ![截图 2024-06-07 14-27-57](https://github.com/dexsuite/dex-retargeting/assets/139104455/9f01ff5a-970a-44bd-9732-1cd19c171ddd) ![截图 2024-06-07 14-38-50](https://github.com/dexsuite/dex-retargeting/assets/139104455/84a4103f-a1fd-414b-b322-6a4d0ed61ba5) ![截图 2024-06-07 14-39-19](https://github.com/dexsuite/dex-retargeting/assets/139104455/6cca5f67-1308-45a6-ab60-65981bd7a1af) ![截图 2024-06-07 14-41-32](https://github.com/dexsuite/dex-retargeting/assets/139104455/304b2535-36e6-48a8-a2a2-d49970e94d69)

Hello, I would like to know how you got the eligible URDF file
